routes/web.php
                Route::get('/{banner}/show', 'BannerController@show')->name('show');
                Route::get('/{banner}/edit', 'BannerController@editForm')->name('edit');
                Route::put('/{banner}/edit', 'BannerController@edit');
                Route::get('/{banner}/file', 'BannerController@fileForm')->name('file');
                Route::put('/{banner}/file', 'BannerController@file');
                Route::post('/{banner}/send', 'BannerController@send')->name('send');
                Route::post('/{banner}/cancel', 'BannerController@cancel')->name('cancel');
                Route::post('/{banner}/order', 'BannerController@order')->name('order');
                Route::delete('/{banner}/destroy', 'BannerController@destroy')->name('destroy');
            });
        Route::group(
            [
                'prefix' => 'messages',
                'as' => 'messages.',
            ],
            function (){
                Route::get('/', 'MessageController@index')->name('index');
                Route::get('/message/show/{dialog}', 'MessageController@show')->name('show');
                Route::post('/message/{dialog}/send', 'MessageController@send')->name('send');
            });
    }
);
Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'namespace' => 'Admin',
        'middleware' => ['auth', 'can:admin-panel'],
    ],
    function (){
        Route::post('/company/{business}/{company}/send', 'CompanyController@send')->name('company.send');
        Route::get('/', 'HomeController@index')->name('home');
        Route::get('removeUser', 'HomeController@removeUser')->name('home.removeUser');
        Route::get('deleteUser', 'HomeController@deleteUser')->name('home.deleteUser');
        Route::get('removeNews', 'HomeController@removeNews')->name('home.removeNews');
        Route::get('deleteNews', 'HomeController@deleteNews')->name('home.deleteNews');
        Route::get('removeCategory', 'HomeController@removeCategory')->name('home.removeCategory');
        Route::get('deleteCategory', 'HomeController@deleteCategory')->name('home.deleteCategory');
        Route::get('removeOrder', 'HomeController@removeOrder')->name('home.removeOrder');
        Route::get('deleteOrder', 'HomeController@deleteOrder')->name('home.deleteOrder');
        Route::post('/users/{user}/verify', 'UsersController@verify')->name('users.verify');
        Route::resource('users', 'UsersController');
        Route::get('/{user}/balance/add', 'UsersController@addMoneyForm')->name('user.balance.add');
        Route::put('/{user}/balance/add', 'UsersController@addMoney')->name('balance.add.save');
        Route::get('/{user}/balance/get', 'UsersController@getMoneyForm')->name('user.balance.get');
        Route::put('/{user}/balance/get', 'UsersController@getMoney')->name('balance.get.save');
        Route::get('/users/{user}/order', 'UsersController@order')->name('users.order');
        Route::resource('pages', 'PageController');
        Route::get('order', 'OrderController@index')->name('order.index');
        Route::get('order/week', 'HomeController@indexWeek')->name('order.indexWeek');
        Route::get('order/week/month', 'HomeController@indexMonth')->name('order.indexMonth');
        Route::resource('regions', 'RegionController');
        Route::resource('news', 'NewsController');
        Route::resource('newscat', 'NewscatController');
        Route::resource('afisha','AfishaController');
        Route::resource('business', 'BusinessController');
        Route::resource('company', 'CompanyController');
        Route::resource('messages', 'MessagesController');
        Route::group(
            [
                'prefix' => 'suggestions',
                'as' => 'suggestions.',
            ],
            function (){
                Route::get('/', 'SuggestionsController@index')->name('index');
                Route::get('/create/{company?}', 'SuggestionsController@create')->name('create');
                Route::post('/store/{company?}', 'SuggestionsController@store')->name('store');
                Route::get('/show/{suggestions?}', 'SuggestionsController@show')->name('show');
                Route::get('/edit/{suggestions?}', 'SuggestionsController@editForm')->name('edit');
                Route::put('/edit/{suggestions?}', 'SuggestionsController@edit');
                Route::get('/photos/{suggestions?}', 'SuggestionsController@photosForm')->name('photos');
                Route::put('/photos/{suggestions?}', 'SuggestionsController@photos');
                Route::delete('/{suggestions}/destroy', 'SuggestionsController@destroy')->name('destroy');
                Route::delete('/photoDelete/{suggestions}/{photo}', 'SuggestionsController@photoDelete')->name('photoDelete');
            });

        Route::group(
            [
                'prefix' => 'business{business}',
                'as' => 'business.',
            ],
            function (){
                Route::post('/first', 'BusinessController@first')->name('first');
                Route::post('/up', 'BusinessController@up')->name('up');
                Route::post('/down', 'BusinessController@down')->name('down');
                Route::post('/last', 'BusinessController@last')->name('last');
                Route::resource('company', 'CompanyController')->except('index');
            });
        Route::group(
            [
                'prefix' => 'pages{page}',
                'as' => 'pages.',
            ],
            function (){
                Route::post('/first', 'PageController@first')->name('first');
                Route::post('/up', 'PageController@up')->name('up');
                Route::post('/down', 'PageController@down')->name('down');
                Route::post('/last', 'PageController@last')->name('last');
            });
        Route::resource('adverts/categories', 'Adverts\CategoryController');
        Route::group(
            [
                'prefix' => 'adverts',
                'as' => 'adverts.',
                'namespace' => 'Adverts',
            ],
            function (){

                Route::get('/new', 'AdvertController@newForm')->name('new');
                Route::post('/new', 'AdvertController@storeNew')->name('new.store');
                Route::post('/{advert}/edit', 'AdvertController@edit');
                Route::resource('categories', 'CategoryController');
                Route::group(
                    [
                        'prefix' => 'categories{category}',
                        'as' => 'categories.',
                    ],
                    function (){
                Route::post('/first', 'CategoryController@first')->name('first');
                Route::post('/up', 'CategoryController@up')->name('up');
                Route::post('/down', 'CategoryController@down')->name('down');
                Route::post('/last', 'CategoryController@last')->name('last');
                Route::resource('attributes', 'AttributeController')->except('index');
                });
                Route::group(
                    [
                        'prefix' => 'adverts',
                        'as' => 'adverts.',
                    ],
                    function (){
                        Route::get('/', 'AdvertController@index')->name('index');
                        Route::get('/create/{user}/{category?}', 'CreateController@category')->name('create');
                        Route::get('/create/region/{user}/{category}/{region?}', 'CreateController@region')->name('create.region');
                        Route::get('/create/advert/{user}/{category}/{region?}', 'CreateController@advert')->name('create.advert');
                        Route::post('/create/advert/{user}/{category}/{region?}', 'CreateController@store')->name('create.advert.store');
                        Route::post('/{advert}/send', 'AdvertController@send')->name('send');
                        Route::get('/{advert}/edit', 'AdvertController@editForm')->name('edit');
                        Route::put('/{advert}/edit', 'AdvertController@edit');
                        Route::get('/{advert}/photos', 'AdvertController@photosForm')->name('photos');
                        Route::post('/{advert}/photos', 'AdvertController@photos');
                        Route::get('/{advert}/attributes', 'AdvertController@attributesForm')->name('attributes');
                        Route::post('/{advert}/attributes', 'AdvertController@attributes');
                        Route::post('/{advert}/moderate', 'AdvertController@moderate')->name('moderate');
                        Route::post('/{advert}/draft', 'AdvertController@sendToDraft')->name('draft');
                        Route::get('/{advert}/reject', 'AdvertController@rejectForm')->name('reject');
                        Route::post('/{advert}/reject', 'AdvertController@reject');
                        Route::delete('/{advert}/destroy', 'AdvertController@destroy')->name('destroy');
                    });
            });
        Route::group(
            [
                'prefix' => 'banners',
                'as' => 'banners.',
            ],
            function (){
                Route::get('/', 'BannerController@index')->name('index');
                Route::get('/{banner}/show', 'BannerController@show')->name('show');
                Route::get('/{banner}/edit', 'BannerController@editForm')->name('edit');
                Route::put('/{banner}/edit', 'BannerController@edit');
                Route::get('/{banner}/file', 'BannerController@fileForm')->name('file');
                Route::put('/{banner}/file', 'BannerController@file');
                Route::post('/{banner}/moderate', 'BannerController@moderateAdmin')->name('moderateAdmin');
                Route::get('/{banner}/reject', 'BannerController@rejectForm')->name('reject');
                Route::post('/{banner}/reject', 'BannerController@reject');

app/Http/Controllers/Admin/NewscatController.php
<?php
/**
 * Created by PhpStorm.
 * User: vlad
 * Date: 30/12/2018
 * Time: 18:51
 */

namespace App\Http\Controllers\Admin;


use App\Entity\NewsCat;
use App\Entity\Page;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class NewscatController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:manage-pages');
    }

    public function index(){
        $newscat = NewsCat::all();
        return view('admin.newscat.index', compact('newscat'));
    }

    public function create(){

        return view('admin.newscat.create');
    }
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|string|max:255',
        ]);

        $newscat = NewsCat::create([
            'title' => $request['title'],
        ]);

        return redirect()->route('admin.newscat.show', $newscat);
    }

    public function show(Newscat $newscat)
    {

        return view('admin.newscat.show', compact('newscat'));
    }

    public function edit(Newscat $newscat)
    {
        return view('admin.newscat.edit', compact('parents','newscat'));
    }

    public function update(Request $request, Newscat $newscat)
    {
        $this->validate($request,[
            'title' => 'required|string|max:255',

        ]);


        $newscat->update([
            'title' => $request['title'],

        ]);

        return redirect()->route('admin.newscat.show', $newscat);
    }

    public function destroy(Newscat $newscat){

        $newscat->delete();

        return redirect()->route('admin.newscat.index');
    }

}

resources/views/admin/newscat/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="panel panel-warning" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
        <div class="panel-body no-padding">
    <form action="{{ route('admin.newscat.store') }}" method="POST" novalidate>
        {{ csrf_field() }}
        <div class="form-group">
            <label for="title">Назва</label>
            <input id="title" name="title" class="form-control{{ $errors->has('title') ? 'is-invalid': '' }}"
                   value="{{ old('name') }}" required>
            @if( $errors->has('title'))
                <span class="invalid-feedback"><stron>{{ $errors->first('title') }}</stron></span>
            @endif
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Зберегти</button>
        </div>
    </form>
        </div>
    </div>
@endsection

resources/views/admin/newscat/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="panel panel-warning" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
        <div class="panel-body no-padding">
            <form method="POST" action="{{ route('admin.newscat.update', $newscat) }}">
                {{ csrf_field() }}
                {{method_field('PUT')}}
                <div class="form-group">
                    <label for="title">Назва</label>
                    <input id="title" name="title" class="form-control{{ $errors->has('title') ? 'is-invalid': '' }}"
                           value="{{ old('title', $newscat->title) }}" required>
                    @if( $errors->has('title'))
                        <span class="invalid-feedback"><stron>{{ $errors->first('title') }}</stron></span>
                    @endif
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Зберегти</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/newscat/index.blade.php
@extends('layouts.admin')

@section('content')
    <p><a href="{{ route('admin.newscat.create') }}" class="btn btn-success " style="margin-bottom: 20px;margin-top: 20px;">Cтворити категорію</a></p>
    <div class="panel panel-warning" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
        <div class="panel-heading"  style="background-color: #8BC34A !important;" >
            <h2>Список категорїй</h2>
            <div class="panel-ctrls" data-actions-container="" data-action-collapse="{&quot;target&quot;: &quot;.panel-body&quot;}"><span class="button-icon has-bg"><i class="ti ti-angle-down"></i></span>
            </div>
        </div>
        <div class="panel-body no-padding" style="display: block;">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Назва</th>
                </tr>
                </thead>

                <tbody>
                @foreach($newscat as $cat)
                    <tr>
                        <td>{{ $cat->id }}</td>
                        <td><a href="{{ route('admin.newscat.show', $cat) }}" target="_self">{{ $cat->title }}</a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/admin/newscat/show.blade.php
@extends('layouts.admin')

@section('content')
    <p><div class="d-flex flex-row mb-3">
        <a href="{{ route('admin.newscat.edit', $newscat) }}" class="btn btn-primary left">Корегувати</a>
        <form method="POST" action="{{ route('admin.newscat.destroy', $newscat) }}">
            {{ csrf_field() }}
            {{method_field('DELETE')}}
            <button class="btn btn-danger left">Видалити</button>
        </form>
    </div></p><br>
    <br>
    <div class="panel panel-warning" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
        <div class="panel-body no-padding">
            <table class="table table-striped">
                <tbody>
                <tr>
                    <th class="warning">ID</th> <td>{{$newscat->id}}</td>
                </tr>
                <tr>
                    <th class="warning">Назва</th> <td>{{$newscat->title}}</td>
                </tr>
            </tbody>
            </table>
        </div>
    </div>
    <div class="card">

    </div>
@endsection