routes/web.php
Route::get('/suggestions/show/{company}/{suggestions}', 'SuggestionsController@show')->name('suggestions.show');
Route::get('/company/{business?}/{region?}', 'CompanyController@index')->name('company');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/verify/{token}', 'Auth\RegisterController@verify')->name('register.verify');
Route::get('/banner/get', 'BannerController@get')->name('banner.get');
Route::get('/banner/{banner}/click', 'BannerController@click')->name('banner.click');
Route::get('/admin/regions/create/{id}', 'Admin\RegionController@create')->name('admin.regions.create');
Route::get('/admin/moderate', 'Admin\ModerationController@index')->name('admin.moderate.index');
Route::post('company/search', 'CompanyController@search')->name('company.search');
Route::group(
    [
        'prefix' => 'adverts',
        'as' => 'adverts.',
        'namespace' => 'Adverts',
    ],
    function (){
        Route::get('/{region?}', 'AdvertController@showTown')->name('showTown');
        Route::post('/search', 'AdvertController@search')->name('search');
        Route::post('/searchAtr/{category?}', 'AdvertController@searchAtr')->name('search.atr');
        Route::get('/show/{advert?}', 'AdvertController@show')->name('show');
        Route::get('/show/user/{user}/all', 'AdvertController@showuserall')->name('show.user.all');
        Route::get('/show/company/{company}/all', 'AdvertController@showcompanyall')->name('show.company.all');
        Route::get('/{advert}/photos', 'AdvertController@photos')->name('photos');
        Route::put('/{advert}/photos', 'AdvertController@save')->name('photos.save');
        Route::post('/show/{advert}/phone', 'AdvertController@phone')->name('phone');
        Route::get('/all/{category?}', 'AdvertController@all')->name('all');
        Route::get('/{region?}/{category?}', 'AdvertController@index')->name('index');
        Route::post('favorites/{advert}', 'FavoriteController@add')->name('favorites');
        Route::delete('favorites/{advert}', 'FavoriteController@remove')->name('favorites');

        Route::post('/message/{advert}', 'MessageController@sendmessage')->name('message');
        Route::post('/message/{advert}/send', 'MessageController@send')->name('message.send');
    }
);
Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'namespace' => 'Cabinet',
        'middleware' => ['auth'],
    ],
    function (){
        Route::get('/', 'HomeController@index')->name('home');

        Route::group(['prefix' =>'profile', 'as' => 'profile.' ], function (){
            Route::get('/', 'ProfileController@index')->name('home');
            Route::get('/edit', 'ProfileController@edit')->name('edit');
            Route::put('/update', 'ProfileController@update')->name('update');
            Route::post('/phone', 'PhoneController@request');
            Route::get('/phone', 'PhoneController@form')->name('phone');
            Route::put('/phone', 'PhoneController@verify')->name('phone.verify');

            Route::post('/phone/auth', 'PhoneController@auth')->name('phone.auth');
        });
        Route::get('/favorites', 'FavoriteController@index')->name('favorites.index');
        Route::delete('favorites/{advert}', 'FavoriteController@remove')->name('favorites.remove');
        Route::resource('tickets','TicketController')->only(['index', 'show', 'create', 'store', 'destroy']);
        Route::post('tickets/{ticket}/message', 'TicketController@message')->name('tickets.message');
        Route::group(
            [
                'prefix' => 'company',
                'as' => 'company.',
                'namespace' => 'Company',
                'middleware' => [App\Http\Middleware\FilledProfile::class],
            ],
            function (){
                Route::get('/', 'CompanyController@index')->name('index');
                Route::get('/create/{business?}', 'CompanyController@business')->name('create');
                Route::get('/create/region/{business}/{region?}', 'CompanyController@region')->name('create.region');
                Route::get('/create/company/{business}/{region?}', 'CompanyController@company')->name('create.company');
                Route::post('/create/company/{business}/{region?}', 'CompanyController@store')->name('create.company.store');
                Route::get('/{company}/edit', 'CompanyController@editForm')->name('edit');
                Route::put('/{company}/edit', 'CompanyController@edit');
                Route::post('/{company}/send', 'CompanyController@send')->name('send');
                Route::delete('/{company}/destroy', 'CompanyController@destroy')->name('destroy');
            });
        Route::group(
            [
                'prefix' => 'adverts',
                'as' => 'adverts.',
                'namespace' => 'Adverts',
                'middleware' => [App\Http\Middleware\FilledProfile::class],
            ],
            function (){
                Route::get('/', 'AdvertController@index')->name('index');
                Route::get('/create/{category?}', 'CreateController@category')->name('create');
                Route::get('/create/region/{category}/{region?}', 'CreateController@region')->name('create.region');
                Route::get('/create/advert/{category}/{region?}', 'CreateController@advert')->name('create.advert');
                Route::post('/create/advert/{category}/{region?}', 'CreateController@store')->name('create.advert.store');
                Route::get('/{advert}/edit', 'ManageController@editForm')->name('edit');
                Route::put('/{advert}/edit', 'ManageController@edit');
                Route::get('/{advert}/photos', 'ManageController@photosForm')->name('photos');
                Route::post('/{advert}/photos', 'ManageController@photos');
                Route::get('/{advert}/company', 'ManageController@companyForm')->name('company');
                Route::put('/{advert}/company', 'ManageController@company');
                Route::get('/{advert}/attributes', 'ManageController@attributesForm')->name('attributes');
                Route::post('/{advert}/attributes', 'ManageController@attributes');
                Route::post('/{advert}/send', 'ManageController@send')->name('send');
                Route::post('/{advert}/close', 'ManageController@close')->name('close');
                Route::delete('/{advert}/destroy', 'ManageController@destroy')->name('destroy');
            });
        Route::group(
            [
                'prefix' => 'banners',
                'as' => 'banners.',
                'namespace' => 'Banners',
                'middleware' => [App\Http\Middleware\FilledProfile::class],
            ],
            function (){
                Route::get('/', 'BannerController@index')->name('index');
                Route::get('/create/{category?}', 'CreateController@category')->name('create');
                Route::get('/all/{category?}', 'CreateController@all')->name('create.reg');
                Route::get('/create/banner/all/{region?}', 'CreateController@bannerall')->name('create.banner.all');
                Route::post('/create/banner/all/{region?}', 'CreateController@storeall')->name('create.banner.storeall');
                Route::get('/create/region/{category?}/{region?}', 'CreateController@region')->name('create.region');
                Route::get('/create/banner/{category?}/{region?}', 'CreateController@banner')->name('create.banner');
                Route::post('/create/banner/{category?}/{region?}', 'CreateController@store')->name('create.banner.store');
                Route::get('/{banner}/show', 'BannerController@show')->name('show');
                Route::get('/{banner}/edit', 'BannerController@editForm')->name('edit');
                Route::put('/{banner}/edit', 'BannerController@edit');
                Route::get('/{banner}/file', 'BannerController@fileForm')->name('file');
                Route::put('/{banner}/file', 'BannerController@file');
                Route::post('/{banner}/send', 'BannerController@send')->name('send');
                Route::post('/{banner}/cancel', 'BannerController@cancel')->name('cancel');
                Route::post('/{banner}/order', 'BannerController@order')->name('order');
                Route::delete('/{banner}/destroy', 'BannerController@destroy')->name('destroy');
            });
        Route::group(
            [
                'prefix' => 'messages',
                'as' => 'messages.',
            ],
            function (){
                Route::get('/', 'MessageController@index')->name('index');
                Route::get('/message/show/{dialog}', 'MessageController@show')->name('show');
                Route::post('/message/{dialog}/send', 'MessageController@send')->name('send');
            });
    }
);
Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'namespace' => 'Admin',
        'middleware' => ['auth', 'can:admin-panel'],
    ],
    function (){
        Route::post('/company/{business}/{company}/send', 'CompanyController@send')->name('company.send');
        Route::get('/', 'HomeController@index')->name('home');
        Route::get('removeUser', 'HomeController@removeUser')->name('home.removeUser');
        Route::get('deleteUser', 'HomeController@deleteUser')->name('home.deleteUser');
        Route::get('removeNews', 'HomeController@removeNews')->name('home.removeNews');
        Route::get('deleteNews', 'HomeController@deleteNews')->name('home.deleteNews');
        Route::get('removeCategory', 'HomeController@removeCategory')->name('home.removeCategory');
        Route::get('deleteCategory', 'HomeController@deleteCategory')->name('home.deleteCategory');
        Route::get('removeOrder', 'HomeController@removeOrder')->name('home.removeOrder');
        Route::get('deleteOrder', 'HomeController@deleteOrder')->name('home.deleteOrder');

app/Http/Controllers/Admin/TicketController.php
<?php
/**
 * Created by PhpStorm.
 * User: vlad
 * Date: 03/12/2018
 * Time: 14:00
 */

namespace App\Http\Controllers\Admin;


use App\Entity\Ticket\Status;
use App\Entity\Ticket\Ticket;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\UseCase\Tickets\TicketService;
use App\Http\Requests\Ticket\MessageRequest;

class TicketController extends Controller
{
    private $service;

    public function __construct(TicketService $service)
    {
        $this->service = $service;
        $this->middleware('can:manage-tickets');
    }

    public function index(Request $request)
    {

        $query = Ticket::orderByDesc('updated_at');

        if (!empty($value = $request->get('id'))){
            $query->where('id', $value);
        }
        if (!empty($value = $request->get('user'))){
            $query->where('user_id', $value);
        }
        if (!empty($value = $request->get('status'))){
            $query->where('status', $value);
        }

        $tickets = $query->paginate(20);

        $statuses = Status::statusesList();

        return view('admin.tickets.index', compact('tickets', 'statuses'));

    }

    public function show(Ticket $ticket)
    {
        return view('admin.tickets.show', compact('ticket'));
    }

    public function editForm(Ticket $ticket)
    {
        return view('admin.tickets.edit', compact('ticket'));
    }

    public function edit(EditRequest $request, Ticket $ticket)
    {
        try{
            $this->service->edit($ticket->id, $request);
        }catch (\DomainException $e){
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('admin.tickets.show', $ticket);
    }

    public function close(Ticket $ticket)
    {
        try{
            $this->service->close(Auth::id(), $ticket->id);
        } catch (\DomainException $e){
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('admin.tickets.show', $ticket);

    }

    public function approve(Ticket $ticket)
    {
        try{
            $this->service->approve(Auth::id(), $ticket->id);
        } catch (\DomainException $e){
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('admin.tickets.show', $ticket);

    }

    public function reopen( Ticket $ticket)
    {
        try{
            $this->service->reopen(Auth::id(), $ticket->id);
        } catch (\DomainException $e){
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('admin.tickets.show', $ticket);

    }

    public function message(MessageRequest $request, Ticket $ticket)
    {
        try{
            $this->service->message(Auth::id(), $ticket->id, $request);
        } catch (\DomainException $e){
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('admin.tickets.show', $ticket);

    }

    public function destroy(Ticket $ticket)
    {
        try{
            $this->service->removeByAdmin($ticket->id);
        } catch (\DomainException $e){
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('admin.tickets.index', $ticket);

    }
}

app/Http/Controllers/Cabinet/TicketController.php
<?php
/**
 * Created by PhpStorm.
 * User: vlad
 * Date: 03/12/2018
 * Time: 13:37
 */

namespace App\Http\Controllers\Cabinet;


use App\Entity\Ticket\Ticket;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use App\UseCase\Tickets\TicketService;
use App\Http\Requests\Ticket\CreateRequest;
use App\Http\Requests\Ticket\MessageRequest;

class TicketController extends Controller
{
    private $service;

    public function __construct(TicketService $service)
    {
        $this->service = $service;
    }

    public function index()
    {
        $tickets = Ticket::forUser(Auth::user())->orderByDesc('updated_at')->paginate(20);

        return view('cabinet.tickets.index', compact('tickets'));
    }

    public function show(Ticket $ticket)
    {
        return view('cabinet.tickets.show', compact('ticket'));
    }

    public function create()
    {
        return view('cabinet.tickets.create');
    }

    public function store(CreateRequest $request)
    {
        try{
            $ticket = $this->service->create(Auth::id(), $request);
        } catch (\DomainException $e){
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('cabinet.tickets.show', $ticket);

    }

    public function message(MessageRequest $request, Ticket $ticket)
    {
        try{
            $this->service->message(Auth::id(), $ticket->id, $request);
        } catch (\DomainException $e){
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('cabinet.tickets.show', $ticket);

    }

    public function destroy(Ticket $ticket)
    {
        $this->checkAccess($ticket);
        try{
            $this->service->removeByOwner($ticket->id);
        } catch (\DomainException $e){
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('cabinet.tickets.index', $ticket);

    }


    public function checkAccess(Ticket $ticket): void
    {
        if (!Gate::allows('manage-own-ticket', $ticket)){
            abort(403);
        }
    }

}

resources/views/admin/tickets/edit.blade.php
@extends('layouts.admin')

@section('content')
@endsection

resources/views/admin/tickets/index.blade.php
@extends('layouts.admin')

@section('content')
    <div style="background-color: azure; position: relative;">
        <div class="card" style="background-color: azure; margin-bottom: 20px">
            <div class="modal-header">
                Фільтер
                <div class="card-body">
                    <form action="?" method="GET">
                        <div class="col-sm-1">
                            <div class="form-group">
                                <label for="id">ID</label>
                                <input class="form-control1 input-search" name="id" id="id" value="{{ request('id') }}">
                            </div>
                        </div>

                        <div class="col-sm-2">
                            <div class="form-group">
                                <label for="user">Користувач</label>
                                <input class="form-control1 input-search" name="user" id="user" value="{{ request('user') }}">
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                <label for="status">Статус</label>
                                <select id="status" class="form-control1 input-search" name="status">
                                    <option value=""></option>
                                    @foreach($statuses as $value => $label)
                                        <option value="{{ $value }}" {{ $value === request('status') ? 'selected' : '' }}>{{ $label }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label class="col-form-label"> </label><br />
                                <button type="submit" class="btn btn-success" style="float: left; margin-left: 5px;">Пошук</button>
                                <a href="?" class="btn btn-warning" style="float: left; margin-left: 5px;">Очистити</a>
                                <a href="{{ route('cabinet.tickets.create') }}" class="btn btn-success" style="float: left; margin-left: 5px;">Створити</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
    </div>
    </div>
    <p></p>
    <div style="position: relative">
        <div class="panel panel-warning" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
            <div class="panel-heading"  style="background-color: #8BC34A !important;" >
                <h2>Список користувачів</h2>
                <div class="panel-ctrls" data-actions-container="" data-action-collapse="{&quot;target&quot;: &quot;.panel-body&quot;}"><span class="button-icon has-bg"><i class="ti ti-angle-down"></i></span></div>
            </div>
            <div class="panel-body no-padding" style="display: block;">
             <table class="table table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>Створено</th>
            <th>Змінено</th>
            <th>Тема листа</th>
            <th>Користувач</th>
            <th>Статус</th>
        </tr>
        </thead>

        <tbody>
        @foreach($tickets as $ticket)
            <tr>
                <td>{{ $ticket->id }}</td>
                <td>{{ $ticket->created_at }}</td>
                <td>{{ $ticket->updated_at }}</td>
                <td><a href="{{ route('admin.tickets.show', $ticket) }}">{{ $ticket->subject }}</a></td>
                <td>{{ $ticket->user->id }}-{{ $ticket->user->name }}</td>
                @if($ticket->isOpen())
                    <td><span class="info">Відкритий</span></td>
                @elseif($ticket->isApproved())
                    <td><span class="primary">Активований</span></td>
                @elseif($ticket->isClosed())
                    <td><span class="errorss">Закритий</span></td>
                @endif
            </tr>
        @endforeach
        </tbody>
    </table>
            </div>
        </div>
    </div>
    {{--{{ $tickets->links() }}--}}
@endsection

resources/views/admin/tickets/show.blade.php
@extends('layouts.admin')

@section('content')
    <p><a href="{{ route('admin.tickets.edit', $ticket) }}" class="btn btn-success" style="float: left;">Корегувати</a></p>
    <p><div class="d-flex flex-row mb-3">
        @if($ticket->isOpen())
            <form  method="POST" action="{{ route('admin.tickets.approve', $ticket) }}">
                {{ csrf_field() }}
                <button class="btn btn-success" style="float: left; margin-left: 5px;">Прийняти</button>
            </form>
        @endif
        @if(!$ticket->isClosed())
            <form  method="POST" action="{{ route('admin.tickets.close', $ticket) }}">
                {{ csrf_field() }}
                <button class="btn btn-success" style="float: left; margin-left: 5px;">Закрити</button>
            </form>
        @endif
        @if($ticket->isClosed())
            <form  method="POST" action="{{ route('admin.tickets.reopen', $ticket) }}">
                {{ csrf_field() }}
                <button class="btn btn-success" style="float: left; margin-left: 5px;">Відкрити</button>
            </form>
        @endif
            <form  method="POST" action="{{ route('admin.tickets.destroy', $ticket) }}">
                {{ csrf_field() }}
                {{method_field('DELETE')}}
                <button class="btn btn-success" style="float: left; margin-left: 5px;">Видалити</button>
            </form>

    </div></p><br>
    <br>
<div class="row">
    <div class="col-md-6">
        <div class="grid_3 grid_5">
            <h3>{{ $ticket->subject }}</h3>
            <div class="but_list">
                <div class="well">
                    {!! nl2br(e($ticket->content)) !!}
                </div>
            </div>
        </div>
    <div class="panel panel-warning" data-widget="{&quot;draggable&quot;: &quot;false&quot;}" data-widget-static="">
        <div class="panel-body no-padding">
            <table class="table table-bordered table-striped pt-2">
                <tbody>
                <tr>
                    <th class="warning">ІD</th> <td>{{$ticket->id}}</td>
                </tr>
                <tr>
                    <th class="warning">Створено</th> <td>{{ $ticket->created_at }}</td>
                </tr>
                <tr>
                    <th class="warning">Змінено</th> <td>{{ $ticket->updated_at }}</td>
                </tr>
                <tr>
                    <th class="warning">Тема</th> <td>{{$ticket->subject}}</td>
                </tr>
                <tr>
                    <th class="warning">Користувач</th> <td><a href="{{route('admin.users.show', $ticket->user)}}" target="_blank">{{$ticket->user->name}}</a></td>
                </tr>
                <tr>
                    <th  class="warning">Статус</th>
                    @if($ticket->isOpen())
                        <td><span class="info">Відкритий</span></td>
                    @elseif($ticket->isApproved())
                        <td><span class="primary">Активований</span></td>
                    @elseif($ticket->isClosed())
                        <td><span class="errorss">Закритий</span></td>
                    @endif
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    </div>
    <div class="col-md-6 email-list1">
        <ul class="collection">
            @foreach($ticket->statuses()->orderBy('id')->with('user')->get() as $status)
            <li class="collection-item avatar email-unread">
                <img src="{{ asset('app/'. $status->user->avatar )}}" alt="{{ $status->user->name }}" width="50" height="50" style="border-radius: 40px; float: left; margin-right: 10px;">
                <div class="avatar_left">
                    <span class="email-title">{{ $status->user->name }}</span>
                    <p class="truncate grey-text ultra-small">{{ $ticket->subject }}</p>
                </div>
                @if($status->isOpen())
                    <a href="{{ route('admin.tickets.show', $ticket) }}" class="secondary-content"><span class="new badge1 blue">Відкритий</span></a>
                @elseif($status->isApproved())
                    <a href="{{ route('admin.tickets.show', $ticket) }}" class="secondary-content"><span class="new badge1 blue1">Прийнятий</span></a>
                @elseif($status->isClosed())
                    <a href="{{ route('admin.tickets.show', $ticket) }}" class="secondary-content"><span class="new badge1 red">Закритий</span></a>
                @endif
                <div class="clearfix"> </div>
            </li>
            @endforeach
        </ul>
    </div>
</div>
    <br>
    <div class="widget_bottom" style="margin-bottom: 70px;">
        <div class="col-md-12 widget_bottom_left">
            <div class="banner-bottom-video-grid-left">
                @php( $i = 1)
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                @foreach($ticket->messages()->orderBy('id')->with('user')->get() as $message)
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="heading{{ $i }}">
                                <h4 class="panel-title asd">
                                    <a class="pa_italic collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ $i }}" aria-expanded="false" aria-controls="collapse{{ $i }}">
                                        <label>{{ $message->created_at }} - {{ $message->user->name }}</label>
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{ $i }}" class="panel-collapse collapse {{ $i === 1 ? 'in' : '' }}" role="tabpanel" aria-labelledby="heading{{ $i }}">
                                <div class="panel-body panel_text">
                                    {!! nl2br(e($message->message)) !!}
                                </div>
                            </div>
                        </div>
                        @php( $i++)
                @endforeach
                </div>
            </div>
        </div>
    @if($ticket->allowsMessage())
        <form action="{{ route('admin.tickets.message', $ticket) }}" method="'GET">
            {{ csrf_field() }}
        <div class="form-group">
            <textarea name="message" id="message" cols="30" rows="4" class="form-control{{ $errors->has('message') ? 'is-invalid' : '' }}" required>{{ old('message') }}</textarea>
        @if($errors->has('message'))
            <span class="invalid-feedback"><strong>{{ $errors->first('message') }}</strong></span>
        @endif
        </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" style="background-color: red; width: 100px; border-radius: 20px; color: white; text-align: center;     margin-top: 5px; border: none;">Відправити</button>
            </div>
        </form>
    @endif
@endsection