routes/web.php
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');

Route::get('cron/advert', 'CronController@advert')->name('cron.advert');
Route::get('cron/banner', 'CronController@banner')->name('cron.banner');
Route::post('/update', 'Admin\Adverts\AdvertController@update');
Route::post('/getCategory', 'Admin\Adverts\AdvertController@getCategory')->name('autocomplete.fetch');
Route::post('/moderationAdvert', 'Admin\Adverts\AdvertController@moderationAdvert')->name('moderation.advert');
Route::post('/orderBanner', 'Admin\Adverts\AdvertController@orderBanner')->name('order.banner');
Route::get('login/facebook', 'Auth\LoginController@redirectToFacebookProvider')->name('login.facebook');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderFacebookCallback');
Route::get('login/google', 'Auth\LoginController@redirectToGoogleProvider')->name('login.google');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderGoogleCallback');
Route::get('/download', function (){
        $file = public_path()."/afisha.xml";
        $headers = array(
            'Content-Type: text/plain'
        );
        return Response::download($file, 'Оголошення-афіша.xml', $headers);
});
Auth::routes();
Route::put('/message', 'HomeController@message')->name('message');
Route::get('/news/category/{category?}', 'NewsController@index')->name('news');
Route::get('/suggestions/show/{company}/{suggestions}', 'SuggestionsController@show')->name('suggestions.show');
Route::get('/company/{business?}/{region?}', 'CompanyController@index')->name('company');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/verify/{token}', 'Auth\RegisterController@verify')->name('register.verify');
Route::get('/banner/get', 'BannerController@get')->name('banner.get');
Route::get('/banner/{banner}/click', 'BannerController@click')->name('banner.click');
Route::get('/admin/regions/create/{id}', 'Admin\RegionController@create')->name('admin.regions.create');
Route::get('/admin/moderate', 'Admin\ModerationController@index')->name('admin.moderate.index');
Route::post('company/search', 'CompanyController@search')->name('company.search');
Route::group(
    [
        'prefix' => 'adverts',
        'as' => 'adverts.',
        'namespace' => 'Adverts',
    ],
    function (){
        Route::get('/{region?}', 'AdvertController@showTown')->name('showTown');
        Route::post('/search', 'AdvertController@search')->name('search');
        Route::post('/searchAtr/{category?}', 'AdvertController@searchAtr')->name('search.atr');
        Route::get('/show/{advert?}', 'AdvertController@show')->name('show');
        Route::get('/show/user/{user}/all', 'AdvertController@showuserall')->name('show.user.all');
        Route::get('/show/company/{company}/all', 'AdvertController@showcompanyall')->name('show.company.all');
        Route::get('/{advert}/photos', 'AdvertController@photos')->name('photos');
        Route::put('/{advert}/photos', 'AdvertController@save')->name('photos.save');
        Route::post('/show/{advert}/phone', 'AdvertController@phone')->name('phone');
        Route::get('/all/{category?}', 'AdvertController@all')->name('all');
        Route::get('/{region?}/{category?}', 'AdvertController@index')->name('index');
        Route::post('favorites/{advert}', 'FavoriteController@add')->name('favorites');
        Route::delete('favorites/{advert}', 'FavoriteController@remove')->name('favorites');

        Route::post('/message/{advert}', 'MessageController@sendmessage')->name('message');
        Route::post('/message/{advert}/send', 'MessageController@send')->name('message.send');
    }
);
Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'namespace' => 'Cabinet',
        'middleware' => ['auth'],
    ],
    function (){
        Route::get('/', 'HomeController@index')->name('home');

        Route::group(['prefix' =>'profile', 'as' => 'profile.' ], function (){
            Route::get('/', 'ProfileController@index')->name('home');
            Route::get('/edit', 'ProfileController@edit')->name('edit');
            Route::put('/update', 'ProfileController@update')->name('update');
            Route::post('/phone', 'PhoneController@request');
            Route::get('/phone', 'PhoneController@form')->name('phone');
            Route::put('/phone', 'PhoneController@verify')->name('phone.verify');

            Route::post('/phone/auth', 'PhoneController@auth')->name('phone.auth');
        });
        Route::get('/favorites', 'FavoriteController@index')->name('favorites.index');
        Route::delete('favorites/{advert}', 'FavoriteController@remove')->name('favorites.remove');
        Route::resource('tickets','TicketController')->only(['index', 'show', 'create', 'store', 'destroy']);
        Route::post('tickets/{ticket}/message', 'TicketController@message')->name('tickets.message');
        Route::group(
            [
                'prefix' => 'company',
                'as' => 'company.',
                'namespace' => 'Company',
                'middleware' => [App\Http\Middleware\FilledProfile::class],
            ],
            function (){
                Route::get('/', 'CompanyController@index')->name('index');
                Route::get('/create/{business?}', 'CompanyController@business')->name('create');
                Route::get('/create/region/{business}/{region?}', 'CompanyController@region')->name('create.region');
                Route::get('/create/company/{business}/{region?}', 'CompanyController@company')->name('create.company');
                Route::post('/create/company/{business}/{region?}', 'CompanyController@store')->name('create.company.store');
                Route::get('/{company}/edit', 'CompanyController@editForm')->name('edit');
                Route::put('/{company}/edit', 'CompanyController@edit');
                Route::post('/{company}/send', 'CompanyController@send')->name('send');
                Route::delete('/{company}/destroy', 'CompanyController@destroy')->name('destroy');
            });
        Route::group(
            [
                'prefix' => 'adverts',
                'as' => 'adverts.',
                'namespace' => 'Adverts',
                'middleware' => [App\Http\Middleware\FilledProfile::class],
            ],
            function (){
                Route::get('/', 'AdvertController@index')->name('index');
                Route::get('/create/{category?}', 'CreateController@category')->name('create');
                Route::get('/create/region/{category}/{region?}', 'CreateController@region')->name('create.region');
                Route::get('/create/advert/{category}/{region?}', 'CreateController@advert')->name('create.advert');
                Route::post('/create/advert/{category}/{region?}', 'CreateController@store')->name('create.advert.store');
                Route::get('/{advert}/edit', 'ManageController@editForm')->name('edit');
                Route::put('/{advert}/edit', 'ManageController@edit');
                Route::get('/{advert}/photos', 'ManageController@photosForm')->name('photos');
                Route::post('/{advert}/photos', 'ManageController@photos');
                Route::get('/{advert}/company', 'ManageController@companyForm')->name('company');
                Route::put('/{advert}/company', 'ManageController@company');
                Route::get('/{advert}/attributes', 'ManageController@attributesForm')->name('attributes');
                Route::post('/{advert}/attributes', 'ManageController@attributes');
                Route::post('/{advert}/send', 'ManageController@send')->name('send');
                Route::post('/{advert}/close', 'ManageController@close')->name('close');
                Route::delete('/{advert}/destroy', 'ManageController@destroy')->name('destroy');
            });
        Route::group(
            [
                'prefix' => 'banners',
                'as' => 'banners.',
                'namespace' => 'Banners',
                'middleware' => [App\Http\Middleware\FilledProfile::class],
            ],
            function (){
                Route::get('/', 'BannerController@index')->name('index');
                Route::get('/create/{category?}', 'CreateController@category')->name('create');
                Route::get('/all/{category?}', 'CreateController@all')->name('create.reg');
                Route::get('/create/banner/all/{region?}', 'CreateController@bannerall')->name('create.banner.all');
                Route::post('/create/banner/all/{region?}', 'CreateController@storeall')->name('create.banner.storeall');
                Route::get('/create/region/{category?}/{region?}', 'CreateController@region')->name('create.region');
                Route::get('/create/banner/{category?}/{region?}', 'CreateController@banner')->name('create.banner');
                Route::post('/create/banner/{category?}/{region?}', 'CreateController@store')->name('create.banner.store');
                Route::get('/{banner}/show', 'BannerController@show')->name('show');
                Route::get('/{banner}/edit', 'BannerController@editForm')->name('edit');
                Route::put('/{banner}/edit', 'BannerController@edit');
                Route::get('/{banner}/file', 'BannerController@fileForm')->name('file');
                Route::put('/{banner}/file', 'BannerController@file');
                Route::post('/{banner}/send', 'BannerController@send')->name('send');
                Route::post('/{banner}/cancel', 'BannerController@cancel')->name('cancel');
                Route::post('/{banner}/order', 'BannerController@order')->name('order');
                Route::delete('/{banner}/destroy', 'BannerController@destroy')->name('destroy');
            });
        Route::group(
            [
                'prefix' => 'messages',
                'as' => 'messages.',
            ],
            function (){

app/Http/Controllers/Adverts/FavoriteController.php
<?php
/**
 * Created by PhpStorm.
 * User: vlad
 * Date: 19/11/2018
 * Time: 21:23
 */

namespace App\Http\Controllers\Adverts;


use App\Entity\Adverts\Advert\Advert;
use App\UseCase\Adverts\FavoriteService;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class FavoriteController extends Controller
{
    private $services;

    public function __construct(FavoriteService $service)
    {
        $this->services = $service;
        $this->middleware('auth');
    }

    public function add(Advert $advert)
    {

        try {
            $this->services->add(Auth::id(), $advert->id);
        } catch (\DomainException $e){
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('adverts.show', $advert)->with('success', 'Оголошення додано до вподобаних.');

    }

    public function remove(Advert $advert)
    {
        try {
            $this->services->remove(Auth::id(), $advert->id);
        } catch (\DomainException $e){
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('adverts.show', $advert);


    }

}

app/Http/Controllers/Cabinet/Adverts/AdvertController.php
<?php
/**
 * Created by PhpStorm.
 * User: vlad
 * Date: 03/11/2018
 * Time: 17:39
 */

namespace App\Http\Controllers\Cabinet\Adverts;

use App\Entity\Adverts\Advert\Advert;
use App\Http\Middleware\FilledProfile;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class AdvertController extends Controller
{
    public function __construct()
    {
        $this->middleware(FilledProfile::class);
    }

    public function index()
    {
        $adverts = Advert::forUser(Auth::user())->orderByDesc('id')->paginate(20);
        return view('cabinet.adverts.index', compact('adverts'));
    }

}

app/Http/Controllers/Cabinet/Adverts/CreateController.php
<?php
/**
 * Created by PhpStorm.
 * User: vlad
 * Date: 04/11/2018
 * Time: 20:51
 */

namespace App\Http\Controllers\Cabinet\Adverts;


use App\Entity\Adverts\Advert\Advert;
use App\Entity\Adverts\Category;
use App\Entity\Region;
use App\Http\Controllers\Controller;
use App\Http\Middleware\FilledProfile;
use App\Http\Requests\Adverts\CreateRequest;
use App\UseCase\Adverts\AdvertService;
use Auth;

class CreateController extends Controller
{
    private $service;

    public function __construct(AdvertService $service)
    {
        $this->service = $service;
        $this->middleware( FilledProfile::class);
    }

    public function category(Category $category = null, Region $region = null)
    {

        if (!empty($category)){
            $categories = Category::where('parent_id', $category->id)->orderBy('name')->get();
            if ($categories->count() < 1){
                $regions = Region::where('parent_id', $region ? $region->id : null)->orderBy('name')->get();
                return view('cabinet.adverts.create.region', compact('category','regions', 'region'));
            }
            if (!empty($categories)){
                return view('cabinet.adverts.create.category', compact('categories'));
            } else{
                $regions = Region::where('parent_id', $region ? $region->id : null)->orderBy('name')->get();
                return view('cabinet.adverts.create.region', compact('category','regions', 'region'));
            }
        }
        $categories = Category::defaultOrder()->withDepth()->get()->toTree();
        return view('cabinet.adverts.create.category', compact('categories'));
    }

    public function region(Category $category, Region $region = null)
    {

        if (!empty($region)){
            $regions = Region::where('parent_id', $region->id)->orderBy('name')->get();
            if ($regions->count() < 1){
                $types = Advert::typeListUser();
                $times = Advert::timeListUser();
                return view('cabinet.adverts.create.advert', compact('category', 'times','region','types'));
            }
        }

        $regions = Region::where('parent_id', $region ? $region->id : null)->orderBy('name')->get();
        return view('cabinet.adverts.create.region', compact('category','regions', 'region'));
    }

    public function advert(Category $category,  Region $region = null)
    {
        $types = Advert::typeListUser();
        if (Auth::user()->isAdmin()){
            $times = Advert::timeListAdmin();
        }else{
            $times = Advert::timeListUser();
        }
        return view('cabinet.adverts.create.advert', compact('category', 'times','region','types'));
    }

    public function store(CreateRequest $request, Category $category, Region $region = null)
    {

        try{
            $advert = $this->service->create(
                Auth::id(),
                $category->id,
                $region ? $region->id : null,
                $request
            );
        } catch (\DomainException $e){
            return back()->with('error', $e->getMessage());
        }

        return redirect()->route('adverts.show', $advert);
    }




}

app/Http/Controllers/Cabinet/FavoriteController.php
<?php
/**
 * Created by PhpStorm.
 * User: vlad
 * Date: 19/11/2018
 * Time: 21:23
 */

namespace App\Http\Controllers\Cabinet;


use App\Entity\Adverts\Advert\Advert;
use App\UseCase\Adverts\FavoriteService;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;


class FavoriteController extends Controller
{
    private $services;

    public function __construct(FavoriteService $service)
    {
        $this->services = $service;
        $this->middleware('auth');
    }

    public function index()
    {
        $adverts = Advert::favoredByUser(Auth::user())->orderByDesc('id')->paginate(20);

        return view('cabinet.favorites.index', compact('adverts'));
    }


    public function remove(Advert $advert)
    {
        try {
            $this->services->remove(Auth::id(), $advert->id);
        } catch (\DomainException $e){
            return back()->with('error', $e->getMessage());
        }
        return redirect()->route('cabinet.favorites.index', $advert);


    }

}

app/Http/Controllers/Cabinet/HomeController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('cabinet.home');
    }
}

resources/views/cabinet/favorites/_nav.blade.php
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-lg-12" style="margin-bottom: 30px;">
            <div class="tab" role="tabpanel">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation"><a href="{{ route('cabinet.home') }}">Кабінет</a></li>
                    <li role="presentation" class="active"><a href="{{ route('cabinet.favorites.index') }}">Вподобані</a></li>
                    <li role="presentation"><a href="{{ route('cabinet.adverts.index') }}">Оголошення</a></li>
                    <li role="presentation"><a href="{{ route('cabinet.banners.index') }}">Мої банери</a></li>
                    <li role="presentation"><a href="{{ route('cabinet.tickets.index') }}">Служба підтримки</a></li>
                    <li role="presentation"><a href="{{ route('cabinet.profile.home') }}">Налащтування</a></li>
                </ul>
                <!-- Tab panes -->
            </div>
        </div>
    </div>
</div>

resources/views/cabinet/favorites/index.blade.php
@extends('layouts.cabinet')

@section('content')
    <div class="row">
        @foreach($adverts as $item)
            <div class="col-sm-6 col-md-4">
                <ul class="">
                    <li itemscope="" itemtype="http://schema.org/Offer" class="_3eDdy">
                        <a title="{{ $item->title }}" class="_2fKRW" data-qa-id="aditem_container" href="{{ route('adverts.show', $item) }}">
                            <div class="_2-jsN"><div class="LazyLoad is-visible">
                                    <div>
                                        <div class="_6ntGx" style="background-image: url(&quot;https://img1.leboncoin.fr/ad-image/fd96e60b12d1c41565d4c3ffd45db7e4a01c2bb6.jpg&quot;);"></div>
                                        <img src="{{  asset('/app/'. $item->avatar ) }}" itemprop="image" content="{{  asset('/app/'. $item->avatar ) }}" alt="subject"></div>
                                </div>
                                <span class="_1sbqp">
                                <div class="_3jAsY">
                                    <div class="_3KcVT">
                                        <span class="_1vK7W" name="spotlight">
                                            <svg viewBox="0 0 24 24" data-name="Calque 1">
                                                <path d="M18.43 0H5.57A2.63 2.63 0 0 0 3 2.67V24l9-4 9 4V2.67A2.63 2.63 0 0 0 18.43 0z"></path>
                                            </svg>
                                        </span>
                                    </div>
                                    <div class="_1MBDf">Оголошення</div>
                                </div>
                            </span>
                            </div>
                            <div class="_3beID">
                                <section class="irAof">
                                    <p class="_3ZfBw">
                                        <span itemprop="name" data-qa-id="aditem_title">{{ $item->title }}</span>
                                    </p>
                                    <p class="_1s5WJ" itemprop="availableAtOrFrom" data-qa-id="aditem_location"><!-- react-text: 2239 -->{{ \Illuminate\Support\Str::limit($item->content,30) }}<!-- /react-text --></p>
                                    <div class="CeFtS" itemprop="priceSpecification" itemscope="" itemtype="http://schema.org/PriceSpecification" data-qa-id="aditem_price">
                                        <meta itemprop="priceCurrency" content="UAH">
                                        <span class="_1_bNq">
                                        <span itemprop="price">{{ $item->price }}</span><!-- react-text: 2244 -->&nbsp;UAH<!-- /react-text --></span>
                                    </div>
                                </section>
                                <div class="_3A9T7"></div>
                            </div>
                        </a>
                        <div class="_3Zm0x" data-qa-id="listitem_save_ad">
                            <div>
                                <div class="_3C4to">
                                    <div class="" data-tip="Sauvegarder l'annonce" data-place="left" data-for="toggleSavedFeaturedAd_1554842308" currentitem="false">
                                    <span class="_1vK7W" name="heartoutline">
                                         <form  method="POST" action="{{ route('cabinet.favorites.remove', $item) }}">
                                             {{ csrf_field() }}
                                             {{method_field('DELETE')}}
                                             <button class="btn btn-sm btn-danger">X</button>
                                        </form>
                                    </span>
                                    </div>
                                    <div class="sc-fjdhpX bpzbGb">
                                        <div class="__react_component_tooltip place-top type-dark " id="toggleSavedFeaturedAd_1554842308" data-id="tooltip"></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </li>
                </ul>
            </div>
        @endforeach
    </div>
            {{ $adverts->links() }}
@endsection